volume_number: 3
isbn: 9784041046562
publication_year: 2017
chapters:
  - title: A Somewhat Old Story
    subtitle: broken bond
    parts:
    - title: null
  - title: Even So, We Live Another Day
    subtitle: stained glass
    parts:
    - title: Smiling Mask
    - title: The Enemy of Regule Aire
    - title: The Returner
    - title: Glimmering Eyes
  - title: Walking Forward, Facing Tomorrow
    subtitle: chained hearts
    parts:
    - title: The City of Cold Rain
    - title: Sleepless Night
    - title: The Division Commander’s Office
    - title: Early Morning
    - title: Fake Red
    - title: Bacon, Salad, and Orange Juice
    - title: Dead Black Agate
  - title: I’ll Stand in Your Way
    subtitle: standing back to back
    parts:
    - title: The Once Strong, Once Mechanized Woman
    - title: Tiat
    - title: The Captive Rebel
    - title: Admired Senior
    - title: Who Stands in the Way
    - title: Who Now Stands Beside
  - title: Lost Kitten
    subtitle: being hungry for kindness
    parts:
      - title: null
