volume_number: 4
isbn: 9784041046579
publication_year: 2017
chapters:
  - title: A Self-Indulgent Fantasy
    subtitle: delusion of dependence
    parts:
      - title: null
  - title: Go After That Felon, And—
    subtitle: who is tagger?
    parts:
      - title: That Day at the 5th Division
      - title: Feodor Jessman
      - title: Reunion
      - title: The Young Man in a Black Suit
      - title: The Pair in the Darkness
      - title: The Winged Guard’s 1st Division
  - title: A Conversation With the Voiceless, Or…
    subtitle: crossing road
    parts:
      - title: Fugitives
      - title: A Running Boy, a Chasing Girl
      - title: The Woman Named Odette Gundakar
