front_cover:
  filepath: "Cover/front.png"

back_cover:
  filepath: "Cover/back.png"

titlepage:
  filepath: "Contents/titlepage.png"

table_of_contents:
  filepath: "Contents/toc.png"

insert:
  - filepath: "Insert/cover-filler.png"
    image_type: "single"
    filler: true
  - filepath: "Insert/insert1.png"
    image_type: "double"
  - filepath: "Insert/insert2.png"
    image_type: "double"

chapter:
  1:
    filepath: "Chapter/1.png"
  2:
    filepath: "Chapter/2.png"
  3:
    filepath: "Chapter/3.png"
  4:
    filepath: "Chapter/4.png"
  5:
    filepath: "Chapter/5.png"
